### PR TITLE
Allow 10 seconds to shutdown, fixing shutdown error

### LINKED ISSUE #132: Error during shutdowncontext deadline exceeded
docker run -d --name fpm-exporter-01 -p 9253:9252 hipages/php-fpm_exporter:v2.0.1,when kill, exit code 1, logs is 'time="2021-02-03T03:44:55Z" level=fatal msg="Error during shutdowncontext deadline exceeded"'

### PR DESCRIPTION
**Pull request by kierenevans**
v2.0.0 and above crashes with message "Error during shutdowncontext deadline exceeded" and exit code 1
upon SIGINT being received (run and then Ctrl+C, or on our case autoscaling a kubernetes deployment down)

v1.2.1 seems to be unaffected.

Possibly due to the change in go versions from v1.14 to v1.15.

The mux graceful shutdown example in https://github.com/gorilla/mux#graceful-shutdown has a usage of the "flag" package to parse an argument into the variable, but it looks like that doesn't happen here so I think it initialised with an empty duration.

Fixes #132

### CODE REVIEW

File: cmd/server.go [hunk 1]
```diff
@@ -103,6 +103,7 @@ to quickly create a Cobra application.`,
 
 		// Create a deadline to wait for.
 		var wait time.Duration
+		wait = time.Second * 15
```
Comment (andytson-inviqa) [inline cmd/server.go:106]:
```suggestion
		wait := time.Second * 15
```

Comment (andytson-inviqa) [reply cmd/server.go:106]: should it be perhaps lower, since the default docker kill timeout is 10 seconds?

Comment (kierenevans) [reply cmd/server.go]: Good point, have reduced to 10 seconds and applied your suggestion for defining directly.

On Kubernetes the default "terminationGracePeriodSeconds" is 30 seconds but this is for the whole pod not just the php-fpm_exporter sidecar, so 10 seconds here allows 20 seconds for php-fpm :+1:

**Review by estahn — APPROVED** [review]
